name: openpgp
description: library for use OpenPGP with support for android and ios, macOS, linux, windows, web and hover
version: 2.0.1
homepage: https://github.com/jerson/flutter-openpgp

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ffi: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.jerson.openpgp
        pluginClass: OpenpgpPlugin
      ios:
        pluginClass: OpenpgpPlugin
      web:
        pluginClass: OpenpgpPlugin
        fileName: web/openpgp_web.dart
      linux:
        pluginClass: OpenpgpPlugin
      macos:
        pluginClass: OpenpgpPlugin
      windows:
        pluginClass: OpenpgpPlugin